In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("dataset.csv")
df.head()

date  precipitation  temp_max  temp_min  wind  weather
0  2012-01-01            0.0      12.8       5.0   4.7  drizzle
1  2012-01-02           10.9      10.6       2.8   4.5     rain
2  2012-01-03            0.8      11.7       7.2   2.3     rain
3  2012-01-04           20.3      12.2       5.6   4.7     rain
4  2012-01-05            1.3       8.9       2.8   6.1     rain

In [3]:
df.shape

(1461, 6)

In [4]:
df1=df.drop("date",axis=1)
df1.head()

precipitation  temp_max  temp_min  wind  weather
0            0.0      12.8       5.0   4.7  drizzle
1           10.9      10.6       2.8   4.5     rain
2            0.8      11.7       7.2   2.3     rain
3           20.3      12.2       5.6   4.7     rain
4            1.3       8.9       2.8   6.1     rain

In [5]:
#seperate daaset into independet and dependent variables

In [6]:
x=df1.iloc[:,:4].values
x

array([[ 0. , 12.8,  5. ,  4.7],
       [10.9, 10.6,  2.8,  4.5],
       [ 0.8, 11.7,  7.2,  2.3],
       ...,
       [ 0. ,  7.2,  0.6,  2.6],
       [ 0. ,  5.6, -1. ,  3.4],
       [ 0. ,  5.6, -2.1,  3.5]], shape=(1461, 4))

In [7]:
y=df1.iloc[:,4].values
y

array(['drizzle', 'rain', 'rain', ..., 'fog', 'sun', 'sun'],
      shape=(1461,), dtype=object)

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=0)

In [9]:
x_test

array([[ 0. , 20. , 12.2,  3.7],
       [ 0. , 10.6,  7.8,  1.4],
       [ 8.4, 14.4, 10. ,  3. ],
       [ 0. , 23.9,  7.8,  5.1],
       [ 0. , 12.8,  7.2,  1.2],
       [19.6, 12.8,  6.7,  5.5],
       [ 1.3, 11.7,  7.8,  2.3],
       [ 4.3, 21.7, 14.4,  2.5],
       [ 0. , 20.6,  8.3,  2.2],
       [ 1. , 13.3,  4.4,  5.1],
       [ 0. , 30. , 16.7,  4.4],
       [12.2,  8.3,  5. ,  1.6],
       [ 0. , 21.1, 14.4,  2.4],
       [ 0. , 26.1, 16.7,  2.2],
       [ 0. , 19.4,  9.4,  1.8],
       [ 0. , 20. ,  8.9,  4.2],
       [ 0. , 25. , 14.4,  3.7],
       [ 5.6,  9.4,  5. ,  4.7],
       [13.5,  8.9,  3.3,  2.7],
       [ 1. , 15. ,  9.4,  5.2],
       [ 6.1, 12.8,  8.9,  4.8],
       [ 7.4, 11.1,  5. ,  4. ],
       [ 8.6, 10. ,  2.8,  5.9],
       [ 0. , 28.9, 15. ,  3.3],
       [ 0. , 27.8, 13.3,  1.9],
       [ 0. , 24.4, 14.4,  4.4],
       [ 0. , 18.3,  9.4,  2.7],
       [ 2.8,  8.9,  6.1,  1.6],
       [ 0. , 23.3, 12.2,  1.9],
       [ 0. , 17.2,  5. ,  2.8],
       [ 0

In [10]:
x_test.shape

(147, 4)

In [11]:
y_test.shape

(147,)

In [12]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)

C:\Users\aditi\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [13]:
y_pred=lr.predict(x_test)
y_pred #predicted value

array(['sun', 'sun', 'rain', 'sun', 'sun', 'rain', 'rain', 'rain', 'sun',
       'rain', 'sun', 'rain', 'sun', 'sun', 'sun', 'sun', 'sun', 'rain',
       'rain', 'rain', 'rain', 'rain', 'rain', 'sun', 'sun', 'sun', 'sun',
       'rain', 'sun', 'sun', 'rain', 'sun', 'rain', 'rain', 'sun', 'rain',
       'sun', 'rain', 'sun', 'rain', 'sun', 'rain', 'rain', 'rain', 'sun',
       'sun', 'sun', 'sun', 'sun', 'sun', 'sun', 'sun', 'sun', 'rain',
       'rain', 'sun', 'sun', 'rain', 'sun', 'rain', 'sun', 'sun', 'sun',
       'sun', 'sun', 'rain', 'sun', 'sun', 'sun', 'rain', 'rain', 'rain',
       'rain', 'sun', 'sun', 'sun', 'sun', 'sun', 'rain', 'rain', 'sun',
       'sun', 'rain', 'rain', 'rain', 'sun', 'sun', 'rain', 'sun', 'rain',
       'sun', 'sun', 'rain', 'sun', 'rain', 'snow', 'sun', 'sun', 'sun',
       'sun', 'rain', 'sun', 'sun', 'rain', 'rain', 'sun', 'rain', 'rain',
       'sun', 'sun', 'rain', 'sun', 'rain', 'sun', 'sun', 'sun', 'sun',
       'sun', 'rain', 'rain', 'sun', 'rain

In [14]:
y_test 

array(['sun', 'sun', 'rain', 'sun', 'sun', 'rain', 'rain', 'rain', 'fog',
       'rain', 'sun', 'rain', 'fog', 'sun', 'sun', 'sun', 'sun', 'rain',
       'rain', 'rain', 'rain', 'rain', 'rain', 'sun', 'sun', 'fog', 'fog',
       'rain', 'fog', 'sun', 'rain', 'sun', 'rain', 'rain', 'sun', 'rain',
       'sun', 'rain', 'fog', 'rain', 'drizzle', 'rain', 'rain', 'rain',
       'drizzle', 'fog', 'fog', 'rain', 'sun', 'sun', 'sun', 'sun', 'sun',
       'rain', 'rain', 'sun', 'sun', 'rain', 'sun', 'rain', 'sun', 'fog',
       'sun', 'sun', 'sun', 'rain', 'sun', 'sun', 'sun', 'rain', 'rain',
       'rain', 'rain', 'sun', 'fog', 'sun', 'sun', 'sun', 'rain', 'rain',
       'fog', 'sun', 'rain', 'rain', 'rain', 'sun', 'fog', 'rain', 'sun',
       'rain', 'sun', 'drizzle', 'rain', 'sun', 'rain', 'snow', 'sun',
       'sun', 'sun', 'rain', 'rain', 'rain', 'rain', 'rain', 'snow',
       'drizzle', 'rain', 'rain', 'sun', 'sun', 'rain', 'sun', 'rain',
       'rain', 'sun', 'sun', 'sun', 'sun', 'rain',

In [15]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm
#sum of right diagonal show how many sample matches (here 121 sample matched)

array([[ 0,  0,  0,  0,  5],
       [ 0,  0,  0,  0, 12],
       [ 0,  0, 60,  0,  8],
       [ 0,  0,  1,  1,  0],
       [ 0,  0,  0,  0, 60]])

In [16]:
y_test.size 
#out of 147 , 121 are matched (82% accuracy rate)

147

In [17]:
import pickle

In [18]:
pickle.dump(lr,open('rfp.pk1','wb'))