In [1]:
import numpy as np

In [2]:
#1d array
a= np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
#2d array
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
a.ndim

1

In [5]:
b.ndim

2

In [6]:
print(a.itemsize)

8


In [7]:
a.dtype

dtype('int64')

In [8]:
a.size

3

In [9]:
b.size

6

In [10]:
a.shape

(3,)

In [11]:
b.shape

(2, 3)

In [12]:
c=b.reshape(3,2)
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
#arange() func is used to create an array of nos in a given range

In [14]:
a1=np.arange(1,5)
a1

array([1, 2, 3, 4])

In [15]:
a2=np.arange(1,11).reshape(2,5)
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [16]:
#ones() func is used to generate matrix of 1's
#zeros() is used to create matrix of 0's

In [17]:
a3=np.ones((2,4)).astype(np.int32)
a3

array([[1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [18]:
a4=np.zeros((3,3)).astype(np.int32) 
a4

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [19]:
a5=np.identity(3).astype(np.int32)
a5

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int32)